name: Cypress Tests

on:
  push:
    branches:
      - testing
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Debug - listar tudo recursivamente
        run: |
          ls -R

      - name: Start Server Backend
        working-directory: server
        run: |
          npm install
          npm start &
          until curl -s http://localhost:8080 > /dev/null; do
            echo "Waiting for backend..."
            sleep 1
          done

      - name: Start Web App Frontend
        working-directory: web
        run: |
          npm install
          npm start &
          until curl -s http://localhost:3000 > /dev/null; do
            echo "Waiting for frontend..."
            sleep 1
          done
          echo "Frontend is running"

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: |
            http://localhost:3000
            http://localhost:8080
          spec: |
            cypress/e2e/cadastro-sucesso.cy.js
            cypress/e2e/login-clinica.cy.js
            cypress/e2e/dashboard.cy.js
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}